export const COLORS = {
  MAIN_BACKGROUND_COLOR: '#ffffff',
  USER_ITEM_GARADIENT_BACKGROUND_COLOR: ['#ffd94a', '#feeb7b'],
  USER_ITEM_GARADIENT_BACKGROUND_COLOR_SELECTED: ['#f5aa6b', '#f6b47e'],
  BORDER_COLOR: '#c5c5af',
  TEXT_COLOR_BLACK: '#000000',
  TEXT_COLOR_WHITE: '#ffffff',
  SHADOW_COLOR: '#000000',
  BUTTON_COLOR_DARK: '#e4b002',
  SEARCH_INPUT_BACKGROUND_COLOR: '#f9f9f9',
};
